-------------------------------------------------------------------------------------------------------------------
--SSSSSSSSSSSSSSSSSSSSSSSS--|--DDDDDDDDDDDDDDDDDD--------|--EEEEEEEEEEEEEEEEEEEEEEEE--|--UUUUU--------------UUUUU--
--SSSSSSSSSSSSSSSSSSSSSSSS--|--DDDDDDDDDDDDDDDDDDDDD-----|--EEEEEEEEEEEEEEEEEEEEEEEE--|--UUUUU--------------UUUUU--
--SSSSS---------------------|--DDDDD--------------DDDDD--|--EEEEE---------------------|--UUUUU--------------UUUUU--
--SSSSS---------------------|--DDDDD--------------DDDDD--|--EEEEE---------------------|--UUUUU--------------UUUUU--
--SSSSSSSSSSSSSSSSSSSSSSSS--|--DDDDD--------------DDDDD--|--EEEEEEEEEEEEEEEEEEEEEEEE--|--UUUUU--------------UUUUU--
--SSSSSSSSSSSSSSSSSSSSSSSS--|--DDDDD--------------DDDDD--|--EEEEEEEEEEEEEEEEEEEEEEEE--|--UUUUU--------------UUUUU--
---------------------SSSSS--|--DDDDD--------------DDDDD--|--EEEEE---------------------|--UUUUU--------------UUUUU--
---------------------SSSSS--|--DDDDD--------------DDDDD--|--EEEEE---------------------|--UUUUU--------------UUUUU--
--SSSSSSSSSSSSSSSSSSSSSSSS--|--DDDDDDDDDDDDDDDDDDDDDDDD--|--EEEEEEEEEEEEEEEEEEEEEEEE--|---UUUUUUUUUUUUUUUUUUUUUUU--
--SSSSSSSSSSSSSSSSSSSSSSSS--|--DDDDDDDDDDDDDDDDDDDDDDDD--|--EEEEEEEEEEEEEEEEEEEEEEEE--|----UUUUUUUUUUUUUUUUUUUUU---

